# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Chen Shangyu
tagline:             
description:         'PhD student at NTU, Singapore'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             
# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
paginate: 5

github:
  repo: https://github.com/csyhhu/
